### ISSUE TITLE
Plugin Error 

### ISSUE THREAD

**Issue by th00mas88** [thinkle/gourmet#1005]
Hi, 

I am very new to this, after playing and getting gourmet working (at last) I was playing with the plugin for default units. When ticking the box in - Settings > Plugin > tools. I get 

> An error occurred activating plugin.
ImportError: No module named unit_display_prefs
You may need to install additional python packages for this module to work properly. If you have a package management system on your computer, use it to search for a package containing "unit_display_prefs", such as "python-unit_display_prefs" or "unit_display_prefs"

checking the folder I have the file unit_display_prefs.gourmet-plugin 

I had a play and unticked "spell check" which no cannot be ticked, 
I am fully lost now.

Thanks

**Comment by cydanil** [comment]
Hi Thomas,
Could you give us more infos on your installation?
* distro;
* Gourmet version;
* how was Gourmet installed.

Thanks!

**Comment by th00mas88** [comment]
Debian ? (I'm running on a pi) 

0.17.5

Using all the instructions listed on the readme. - initially I had used the zip and unzipped to documents and installed from there but I kept getting fails so went back and used the tarball

**Comment by cydanil** [comment]
I know this is a bit dated.  
You should however now be able to run Gourmet as intended on raspian:

- Install the dependencies as listed in the [installation instructions](https://github.com/thinkle/gourmet/blob/master/INSTALL.md#unbutu-2004-linux-mint-20)

- Clone the repository;
- within the folder, do 
```
python3 setup.py build_i18n
pip3 install .
```

**Comment by th00mas88** [comment]
Hey.

Thanks I thought I had self replied. I ended up finding the pip install and
doing that . I'm quite new to all pi stuff so I'm not sure what I was doing
wrong. But the pip worked!
