### ISSUE TITLE
XSD for input file ?

### ISSUE THREAD

**Issue by Lamisedaxeh** [thinkle/gourmet#1006]
I can't find an xsd or something like that for the input file "grmt" (or any other input file (i can't find krecipe.xsd :( )).
There is a page on the wiki with some info about the file input but it's not really readable.
And there is 3 file on the page witch one are used in the project ?

PS: im writing a parser to parse recipe from marmiton.org to grm

**Comment by FriedrichFroebel** [comment]
There is a DTD available at https://github.com/thinkle/gourmet/blob/master/data/recipe.dtd.

**Comment by Lamisedaxeh** [comment]
OH Thanks !
I forget to check for dtd file x(
