### ISSUE TITLE
html export with microdata or microformats support

### ISSUE THREAD

**Issue by ockham** [thinkle/gourmet#31]
Converted from [SourceForge issue 3565626](https://sourceforge.net/support/tracker.php?aid=3565626), submitted by [SourceForge user no. 3480783](https://sourceforge.net/users/?user_id=3480783) on 2012-09-07 17:10:03 UTC.

I would love two things:
1. html export with a rich snippets (microdata, microformats, and RDFa) tagging (better if we can choose between standards)
2. html should not have any formatting, CSS could be used instead.
Once the html export tagging is implemented, css formatting would be very easy, sort of skinnable.
I'm not able to develop such export plugin feature, but I could contribute writiung CSS to create such skins (screen/ipade/print ready).
It would be also be great for the export plugin to be able to create an index page to linking to all the axported recipes, when exporting many.
References:
http://microformats.org/wiki/hrecipe
http://schema.org/Recipe
I would be glad to contribute, but I'm not a programmer.

**Comment by Lamecarlate** [comment]
I would like to reopen this issue: microdata (itemscope, itemprop, etc) do not work with html4, only with html5.
