### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by ockham** [thinkle/gourmet#697]
As there is no PyGTK for Python 3, we need to first fix issue #696.

Make sure our requirements are available not only for Linux, but at least also for Windows. Current state of some Windows dependecies:
- PyGTK: Only available for Python 2.6 and 2.7. PyGI is Python 3 compatible, see #696.
- SQLAlchemy: Available for Python 2.5 through the latest 3.x.
- PyWin: Available also for Python 3.1 and 3.2.
- PIL: Available only for 2.6 and 2.7; but there's [Pillow](http://python-imaging.github.io/) which is Python 3 compatible. OTOH, we might remove our PIL dependency altogether (see #706).

**Comment by maweki** [comment]
How is the progress on this? I did some work at the end of last year (using py2->3 migratory scripts and a lot of commenting out and renaming) that, at least, brought the GUI up so Gourmet started with python3 without erroring out.

https://github.com/maweki/gourmet/commit/d93cd02f76f907ed441d018b237e128a530ebc59

**Comment by saxon-s** [comment]
I started cleaning up the Gourmet code base some time back in preparation to migrate to Python 3 and GTK+ 3. Unfortunately, my paid job keeps on hindering my progress. :-( 

There appears to be community interest in migrating Gourmet to Python 3. Your help is needed!

I've created two new Gourmet branches off `master`:
- `py2-gourmet`: to preserve the Python 2.7 version of Gourmet for prosperity.
- `py3-migration`: for migrating Gourmet to Python 3. 

Using a feature branch will allow master to represent the official history and to be buildable/deployable during the Python 3 migration. Once the migration is complete, the feature branch will be merged back to `master`.

I've created simple GitHub CI workflows for `master` (Python 2.7) and `py3-migration` (Python 3.8). They both fail `flake8` at this time. 

If you are interested in helping in migrating Gourmet to Python 3 please join the newly created Slack workspace gourmet-recipe-manger:
https://join.slack.com/t/gourmet-github/shared_invite/zt-e3t9zik1-aelzozuTMZuHGqpY~t8jUQ

I look forward to your support in migrating Gourmet to Python 3.

**Comment by maweki** [comment]
We're making quite some progress over at https://github.com/kirienko/gourmet

We have the main window running under python 3

**Comment by spaetz** [comment]
Thanks for the hint @maweki. To be honest, this is great and I would propose to pull this in as a whole and re-integrate those efforts. In my current debian-testing gourmet is THE only thing holding back python2, which is a pity when somebody has invested all the efforts to modernize this great program.
