### ISSUE TITLE
Printing recipes with Polish letters

### ISSUE THREAD

**Issue by krzyklo** [thinkle/gourmet#729]
When I am trying to print recipe, I get black squares instead of polish letters:

![example](https://f.cloud.github.com/assets/1746970/1461531/32c71c62-44b8-11e3-8d65-387ddcf6f113.png)

The same error as above exists in PDF document, which I get when I clik Print Preview.

In recipe view Polish letters are displayed correctly. To get correct export, I need to do Plain text export or HTML export, and then print resulting file, but it is annoying to exporting to file to print.
I didn't find any options to set encoding of PDF files...
Is someone could point me how to fix this annoying issue?

**Comment by marmistrz** [comment]
Maybe a temporary solution to select the .ttf file via the file browser would be feasible until a proper one is implemented?

**Comment by pabru** [comment]
I propose detecting if non-Latin-2 characters are present in the recipe while exporting to PDF, and if that's detected, then embed a cut-down version of a font which includes only the character descriptions for the characters actually present in the document. I'm quite sure PDF allows you to do that.

If this option is chosen as default, it should be easy to use for non-technical users and save some space in the exported file at the same time. There could be extra options for advanced users to choose their own font and/or choose whether to embed the full or cut-down versions.

Any idea which parts of the source I should be looking at to get started?

**Comment by krzyklo** [comment]
Again the same issue in version 0.17.4, but this time the code in ../gourmet/plugins/import_export/ changed ,and gist from Ockham: https://gist.github.com/ockham/7362154  do not work anymore.
Would someone more familiar with the code could advice, where to modify the font settings, to stop getting this kind of error? 
Kind Regards,

**Comment by krzyklo** [comment]
It is surprising, that no one could help with such regression like this. 
Could anyone advice how to fix it?

**Comment by krzyklo** [comment]
In 2020 again, trying to print gives black squares, and the solution given by Ockham no longer applicable, as the way how files are organized are changed.
Could anyone explain, where to search in files for fontName settings? 
Tried to grep for "fontName" but it not returned any hit. 
It seems, that the way how page for print is generated changed completely.
Could anyone suggest where to change the font used for printing?
