### ISSUE TITLE
Use Unicode everywhere

### ISSUE THREAD

**Issue by ockham** [thinkle/gourmet#736]
In order to avoid nasty little bugs such as #734, we should probably use Unicode in every part of the program instead of other encodings. That includes:
- The source code
- Literal strings
- string columns in the database
- GUI strings (in .ui files)
- Translations (in .po files)
- Exporters (e.g. PDF export via reportlab)

**Comment by andrearicci** [comment]
Hello, Japanese is completely lost in pdf export (windows installation - see attached sample: the black squares' lines) is that related to the same issue? Or shall I open a new one? Is there any work around?
[Cavolo e Maiale (Hoiko-rou).pdf](https://github.com/thinkle/gourmet/files/359476/Cavolo.e.Maiale.Hoiko-rou.pdf)
This was just a note in an Italian recipe, but we have full recipes in Japanese that can't be printed.
Thank you
