### ISSUE TITLE
searching for ragu should find also ragù

### ISSUE THREAD

**Issue by andrearicci** [thinkle/gourmet#748]
I would like that the default search could be found also accented voals. I mean that searching "ragu" should find also "ragù".
I guess this could be done through a regex search, but I would like it to be implemented as a default search behaviour, so even people that don't know regex can easilly find its recipe.
Thank you

**Comment by alxcord** [comment]
I think somethin like beets fuzzy plugin would be really nice
https://github.com/sampsyo/beets/blob/v1.3.15/docs/plugins/fuzzy.rst
