### ISSUE TITLE
Pantry manager

### ISSUE THREAD

**Issue by ockham** [thinkle/gourmet#75]
Converted from [SourceForge issue 1485001](https://sourceforge.net/support/tracker.php?aid=1485001), submitted by [SourceForge user smandal](https://sourceforge.net/users/?user_id=49474) on 2006-05-09 20:33:26 UTC.

Some listing of what ingredients one has on stock, to
cross-reference with shopping list.  Maybe information
of when listings expire/spoil.

Thanks!  This application is addictive.  Some bugs
ingesting the instructions in Epicurious recipes, but
otherwise every usable.

**Comment by siddharthist** [comment]
This is presently a feature of gourmet, this issue can be safely closed.

**Comment by ockham** [comment]
Thanks @siddharthist!
