### ISSUE TITLE
AllRecipes Importer doesn't work.

### ISSUE THREAD

**Issue by denali1** [thinkle/gourmet#786]
Based on the previous bug, I'm assuming the format of the page has changed again.  Unfortunately, I couldn't find a log to post.

Essentially, I give it the web address.  It downloads the page, but doesn't create a new recipe entry.

**Comment by JD4x4** [comment]
Have the same problem on my win 8.1 tablet. First time I've used it since last app upgrade. Was going to see if it was an issue on my linux machine but haven't yet.
