### ISSUE TITLE
Note for Fedora installers - dependencies

### ISSUE THREAD

**Issue by georgerapp** [thinkle/gourmet#795]
After downloading and un-tarring the 0.17.4 release on my Fedora (21) machine, because Fedora only offers version 0.16.0 in their official repositories, I reviewed the INSTALL.md file, which suggested the following command:

$ python setup.py --help
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from DistUtilsExtra.command import build_extra, build_i18n, build_icons
ImportError: No module named DistUtilsExtra.command

I was able to get around this error by installing a package using yum:

\# yum install python-distutils-extra

Edit: also found another required package when installing:

running build_i18n
intltool-update -p -g gourmet
unable to execute intltool-update: No such file or directory
error: command 'intltool-update' failed with exit status 1

This is, in turn, easy to fix with another package installation:

\# yum install intltool

Suggest updating INSTALL.md with this information.

**Comment by ockham** [comment]
Thanks for your report.

I'm surprised you can't install 0.17.4 from the official Fedora 21 repos; I myself am running Fedora 21 these days, and installing Gourmet from the repos gives me 0.17.4, as is backed up by https://apps.fedoraproject.org/packages/gourmet/overview/

Both `python-distutils-extra` and `intltool` are already listed in the table at the bottom of [INSTALL.md](https://github.com/thinkle/gourmet/blob/master/INSTALL.md) (even though it doesn't have an explicit Fedora column yet) -- but maybe that file is just a bit TL;DR?

**Comment by georgerapp** [comment]
Uh, yeah, I could have answered my own question - I'm still back on Fedora 20 on the machine I was testing on, thus I'm topped out at version 0.16.0-2.fc20. I'll FedUp the box this weekend and try it again.

Closing this comment because I wasn't paying attention to which box I was on ... 8^)
