### ISSUE TITLE
(Bug) Unable to edit or add recipes 

### ISSUE THREAD

**Issue by Lailah** [thinkle/gourmet#821]
I'm using Manjaro. And after the last Python / SQL Alchemy  update I'm not able anymore of adding new recipes or editing the saved ones. 
I use this programme a lot. Is it possible to fix it? 
Thanks in advance!!

**Comment by jeremyrjk** [comment]
For me, I'm also not able to use any of the recipes. If I open a recipe card the only thing visible is the ingredients and picture. Everything else is empty.

**Comment by Lailah** [comment]
I do can see recipes. But not edit them. Or add a new recipe. If I try
to add a new recipe, a new item is added. I can see it as  "new
recipe", but of course it has no title or anything because the new
recipe window is hanged.

**Comment by NP-Hardass** [comment]
Pillow deprecated a number of functions, in particular Image.tostring.  Starting with Pillow 3.0.0, these deprecated functions have been removed and replaced with exceptions.  https://github.com/python-pillow/Pillow/commit/89ccf66ff7f2646c3e649d6a3bba0a7e1c38a99e#diff-3fef5f960d5bd8bdfb9c6fadcf96af22

As such, https://github.com/thinkle/gourmet/pull/823 or https://github.com/thinkle/gourmet/pull/824 should resolve this issue, I suspect.

**Comment by Lailah** [comment]
Thank you!!
I guess this solution will reach, in some time, the distributions, right?
I'm currently using Fedora, and my sister is using Manjaro.
Thanks again!

**Comment by flasheater** [comment]
Experiencing the same issue on Fedora 23 with Gourmet 0.17.4.

[http://i.imgur.com/dq9Xp5l.jpg](Screenshot)
[http://hastebin.com/bisavetogi.rb](Error Log)

**Comment by Lailah** [comment]
I reported this bug to Fedora and they uploaded the fix to
updates-testing.  But I'm still waiting to see it in stable.
I'm on Fedora 23 Cinnamon right now.

**Comment by Lailah** [comment]
Just tried the update. It works!!

Thanks.
