### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Tharbad** [thinkle/gourmet#826]
Can you add this to INSTALL.md please?

I got this error:
<user>@<pc-name>:~/Downloads/gourmet$ sudo python setup.py install
[sudo] password for <user>: 
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from DistUtilsExtra.command import build_extra, build_i18n, build_icons
ImportError: No module named DistUtilsExtra.command

After some research I found out that I need to install "python-distutils-extra".
Note that this package is for python 2.7. 
There is another package called "python3-distutils-extra" for python 3 so don't get confused.

Thanks

**Comment by ockham** [comment]
It's mentioned there already, right below 'Build Requirements'.
