### ISSUE TITLE
which is the code that expors to html?

### ISSUE THREAD

**Issue by andrearicci** [thinkle/gourmet#827]
I would like to implement my styles for the html exporter, but I could'nt find the code!
I'm not a coder, just an amateur html+css developer, but maybe this can make me start playing with python. Where to start?
Thank you.

**Comment by thinkle** [comment]
There's CSS in the output so start by playing with that

**Comment by thinkle** [comment]
More specifically, you can play with data/style/default.css

**Comment by andrearicci** [comment]
thank you, but what about the html exporting system? if I want to work on the tags?

**Comment by thinkle** [comment]
Shouldn't be necessary if you want to change style, but you can look
at gourmet/gourmet/plugins/import_export/html_plugin/html_exporter.py

**Comment by andrearicci** [comment]
Thank you
