### ISSUE TITLE
formating instructions

### ISSUE THREAD

**Issue by alpinekid** [thinkle/gourmet#829]
Is there a way for format instructions, like using a subset of  xhtml tags.

**Comment by googlymog** [comment]
Hello alpinekid,

There is already some degree of formatting in Gourmet in a couple of the menus.  I just tried using a \<p\> tag and the string '\<p\>' showed up after saving, so I doubt any xhtml tags will work.  In the edit menu for instructions there is an option for bold, underline and italic.  Additionally, tabs and whitespace are preserved.  I also tried copying and pasting a bullet point from a google search and that was still present after saving.

Is this what you want as far as formatting is concerned?  If not, could you elaborate.  Thanks.
