### ISSUE TITLE
GTK / Glade error when trying to run Gourmet

### ISSUE THREAD

**Issue by jeremyrjk** [thinkle/gourmet#835]
Running setup.py works. However, Gourmet does not run and gives this error:

```
[jeremy@jeremy ~]$ gourmet
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "/usr/bin/gourmet", line 17, in <module>
    GourmetRecipeManager.startGUI()
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 686, in startGUI
    r=RecGui(splash_label=splash.label)
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 896, in __init__
    GourmetApplication.__init__(self, splash_label=splash_label)
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 67, in __init__
    self.setup_prefs() # Setup preferences...
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 89, in setup_prefs
    buttons={'clear_remembered_optional_button':lambda *args: self.forget_remembered_optional_ingredients()}
  File "/usr/lib/python2.7/site-packages/gourmet/prefsGui.py", line 60, in __init__
    self.ui.add_from_file(uifile)
glib.GError: Invalid root element: 'html'
```

**Comment by googlymog** [comment]
Not sure if this will be helpful, but I have recreated your error.

The variable uifile points to '/usr/local/share/ui/preferenceDialog.ui'.  The preferenceDialog.ui file should NOT have an \<html\> element in it.  I added one to my preferenceDialog.ui file and that successfully recreated the traceback you reported.  (Thanks for including the traceback).  Can you open the preferenceDialog.ui file and check to see if \<html\> or the string html is present?  The only root elements should be <?xml version="1.0" encoding="UTF-8"?> and \<interface\>.

If that doesn't work, which version of gourmet are you using?  Did you clone the source from github recently and install from that?

**Comment by jeremyrjk** [comment]
Success!! :-)

I had to copy contents of the folder.../gourmet-master/ui  (the source that I downloaded from github) to /usr/share/ui

Everything seems to be working properly now.
Thanks so much!!

**Comment by googlymog** [comment]
Great to hear!  Thanks for communicating your solution.

This ticket can be closed now.

**Comment by thinkle** [comment]
I know I was doing some recent testing and it appeared the directories in
settings.py were off. It's possible a recent patch of mine would also fix
this.
