### ISSUE TITLE
Error following web links in Kubuntu 14.04

### ISSUE THREAD

**Issue by allenerenee** [thinkle/gourmet#840]
I import a lot of my recipes from various websites, and for a long while the link in the recipe card was clickable. Couldn't tell you when it started (I've been working around it for a while), but now when I try to follow one of those links I get the following error:

> Traceback (most recent call last):
>  File "/usr/lib/python2.7/dist-packages/gourmet/reccard.py", line 616, in link_cb
>    def link_cb (self, *args): launch_url(self.link)
> NameError: global name 'launch_url' is not defined

Anyone else having this problem?

**Comment by thinkle** [comment]
That's odd. Looking at the latest source, I see launch_url is still getting
imported from gglobals properly and, indeed, the callback still works.

I wonder if a temporary bug was introduced at some point that got packaged
up in kubuntu.

Does line 23 of your reccard.py look like this (or does this line exist at
all in reccard.py):
from gglobals import FLOAT_REC_ATTRS, INT_REC_ATTRS, REC_ATTR_DIC,
REC_ATTRS, doc_base, uibase, imagedir, launch_url

At any rate, that should be the fix to that error, but I'm not sure how a
version got packaged without that element imported.

Tom

**Comment by allenerenee** [comment]
Hm. Well, that did fix the launch issue. Unfortunately, my idea for what might have caused it was wrong, so I still couldn't guess how it might have made it out without the "launch_url" element. (The rest of the line was there.)

Had a theory that it might have been caused by disabling the nutrition stats plugin, so I tested that. No dice. Posting the errors thrown for that below for reference, but will cross-post in a more pertinent location.

When disabling the plugin:
>Traceback (most recent call last):
>  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_gui.py", line 95, in toggled_cb
>    self.do_change_plugin(plugin_set, state, ls)
>  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_gui.py", line 130, in do_change_plugin
>    self.loader.deactivate_plugin_set(plugin_set)
>  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 182, in deactivate_plugin_set
>    self.instantiated_plugins[plugin].remove()
>  File "/usr/lib/python2.7/dist-packages/gourmet/plugin.py", line 246, in remove
>    self.db.remove_hook(plugin_loader.POST,'setup_tables',self.create_tables)
>  File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 367, in remove_hook
>    del hookdic[name]
>KeyError: 'setup_tables'

Following a link after disabling the plugin and relaunching:
>(firefox:32020): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(times about 3) My guess is this is a Firefox issue, but my coding skills mostly consist of Google-fu, I'm afraid.
