### ISSUE TITLE
Apparent error when disabling nutrition database plugin

### ISSUE THREAD

**Issue by allenerenee** [thinkle/gourmet#841]
Testing something for a previous issue in Kubuntu 14.04, I re-enabled and then disabled the nutrition database to see what happened. Received a message that there was an error when disabling the plugin:
>Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/gourmet/plugin_gui.py", line 95, in toggled_cb
self.do_change_plugin(plugin_set, state, ls)
File "/usr/lib/python2.7/dist-packages/gourmet/plugin_gui.py", line 130, in do_change_plugin
self.loader.deactivate_plugin_set(plugin_set)
File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 182, in deactivate_plugin_set
self.instantiated_plugins[plugin].remove()
File "/usr/lib/python2.7/dist-packages/gourmet/plugin.py", line 246, in remove
self.db.remove_hook(plugin_loader.POST,'setup_tables',self.create_tables)
File "/usr/lib/python2.7/dist-packages/gourmet/plugin_loader.py", line 367, in remove_hook
del hookdic[name]
KeyError: 'setup_tables'

Closed Gourmet and relaunched, and the nutrition tab had been removed from the recipe card as expected - thus, I'm not sure what effect this error actually had. Left my terminal open and followed a recipe card link, and it looks like now it's fighting with Firefox:

>(firefox:32020): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

repeated 4 times. Got the same thing on a different card, except it was firefox:32105. I'm afraid I'm not really a programmer to even know what that means, but I hope it's useful to someone doing stress testing.

**Comment by googlymog** [comment]
I can reproduce this error and traceback with the latest source by enabling and disabling the plugin, as allenerenee reports.  Similarly, when I exit and restart Gourmet the plugin is disabled and everything seems to be fine.  I didn't experience problems or warnings launching a url from a recipe card, so that might be a separate issue.
