### ISSUE TITLE
Feature Request: Stylized Menus to Help when Cooking

### ISSUE THREAD

**Issue by NYVegan** [thinkle/gourmet#888]
See here: http://www.recipedesignwizard.com/RecipeDesignWizard.pdf for an example.  The recipes take less space and are easier to use.

[1st github contribution.  My apologies if this isn't appropriate or relevant]

**Comment by dyoung418** [comment]
Appreciate the suggestion.  My sense is that this is a fairly major change to the way recipes are both stored and displayed.  Given the current conversations about priorities on this program among the developers, I think this is unlikely to get implemented
