### ISSUE TITLE
Printing on Ubuntu removed

### ISSUE THREAD

**Issue by alankjackson** [thinkle/gourmet#909]
Print capabiity has been intentionally removed from Ubuntu.
This really cripples the product.
At minimum the error messages could be updated to something useful.
==========
This was dropped because it depended on obsolete gnome printing
libraries that were being removed:

gourmet (0.17.4-5) unstable; urgency=medium

  * Remove python-poppler dependency and remove print_plugin.py plugin.

 -- Christian Marillat <marillat@debian.org>  Fri, 05 Jan 2018 16:34:39
+0100

Re-adding support for printing would require a new implementation, which
ought to be handled through upstream.

** Changed in: gourmet (Ubuntu)
       Status: New => Won't Fix

**Comment by HaraldFranzen** [comment]
I have been searching all day for a fix; this issue will kill Gourmet....
Is anybody talking to "upstream"?

**Comment by micahcochran** [comment]
That message was from the package maintainers for Debian/Ubuntu.  In that context, "upstream" means this project.

**Comment by kmacneil** [comment]
The [bug report](https://bugs.launchpad.net/ubuntu/+source/lernid/+bug/1739622) says "python-poppler will be removed from Debian and Ubuntu soon. Please don't have lernid depend on python-poppler. It is instead recommended to switch to gtk3 and GObject Introspection bindings." I assume the expectation is that some alternate method should be provided that will allow re-adding the missing features with little or no work. My guess is this is not going to happen.

Workaround: One of the export methods that is still supported is My Cookbook mdb files. I bulk exported 100+ recipes to an mdb file and installed the My Cookbook Pro Android app. One of My Cookbook's supported import methods is upload from Dropbox (the other being SD card), so I uploaded the mdb file there and imported it. The formatting and layout are not perfect but they're good enough, and at least now I can get my recipes onto a portable device more suitable for the kitchen.

**Comment by joelswartz** [comment]
See this link:
https://askubuntu.com/questions/1185579/printing-pdf-export-plugin-for-gourmet-recipe-manager-0-17-4
Fixed the problem for me on Linux neon, based on Ubuntu 18.04. I can now print, export all.
