### ISSUE TITLE
Building with setup.py bdist

### ISSUE THREAD

**Issue by langston-barrett** [thinkle/gourmet#911]
I'd like to package `gourmet` for `NixOS`. The default build process there is to use `bdist_wheel` and then install the items in the archive. This has given me some strange results. For instance,
```
python setup.py bdist
cd dist/
tar xvf *
cd [extracted path]/bin
export PYTHONPATH=$PYTHONPATH:../lib/python2.7/site-packages
./gourmet
```
yields
```
glib.GError: Failed to open file '/home/siddharthist/code/gourmet/dist/nix/store/2k0ap4hvl25rxlwhhva9ydhcsx8z3p0k-python-2.7.15/lib/python2.7/site-packages/gourmet/../data/images/AddToShoppingList.png': No such file or directory
```
It seems that Gourmet, when build with the `bdist` option (or `bdist_wheel`), expects a directory layout that it doesn't get. Is there a way to make Gourmet work well with `bdist`?

**Comment by FriedrichFroebel** [comment]
The master branch is known to be broken (see #910 for example), but using the latest release 0.17.4 from June 2014 seems to work.

**Comment by siddharthist** [comment]
@FriedrichFroebel I'm having this problem on 0.17.4 with `bdist_wheel`.
