### ISSUE TITLE
Plaintext database, git integration, etc.

### ISSUE THREAD

**Issue by marmistrz** [thinkle/gourmet#912]
Hi!

I've tried using Gourmet a couple of times and I've always come against a showstopper - the ability to backup the database, and keep track, what has been backed up and what not. At least once I lost my recipes due to the fact that there's no easy way to keep them backed up.

In my opinion, a good solution would make it possible to store the recipes database in git and get human-readable diffs. Preferably, each recipe in a separate file. This makes just dumping the `recipe` table a dubious idea - I'm not sure if we want to store some hashes in such a dump. I rather think about just dumping the whole recipe list to a user-defined directory, to the gourmetDoc XML format (I think it's the one best suited out of the available ones), one recipe in a file, after each database save. This would make it really easy - just commit & push to the repository or use some cloud sync if you're not into git.

What do you think about such solution?
I'm willing to contribute the change - otherwise I'd just need to roll my own recipe management solution :)

**Comment by thinkle** [comment]
Seems like a fine plugin to me. I'm not sure if there are hooks built in to
let plugins act on save but it should be simple to add them if they're not
already there.

**Comment by marmistrz** [comment]
I actually ended up using plain markdown+git for storing recipes. I will reopen if it's not enough for me. :)
