### ISSUE TITLE
Import webpage doesn't work

### ISSUE THREAD

**Issue by Lailah** [thinkle/gourmet#915]
There's an option in Gourmet to import pages. One clicks there and pop-up windows appears asking for the page's URL.  After adding the link and accepting, it doesn't add any recipe at all.  I tried closing and opening the app but still no luck. There are no recipes in the list.
OS:  Windows 10

**Comment by saxon-s** [comment]
Please provide the Gourmet version number.

**Comment by Lailah** [comment]
Gourmet Recipe Manager 0.17.4

**Comment by saxon-s** [comment]
Tested version 0.17.4

Confirmed issue exists on Windows 10

Issue does not exist on Ubuntu 18.04

**Steps to reproduce issue:**

1. Click menu: `File` --> `Import webpage` 
2. Enter website address: `https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/`
3. Click: `OK`
4. Progress bar appears and message `Recipe successfully imported` is displayed
5. "Import recipe" dialog not displayed
6. Recipe not added to recipe database

**Comment by Lailah** [comment]
Yes, exactly. In my case, with a different recipe, it would fail to import altogether.  But using the link you provided it shows a progress bar and the message  "Recipe successfully imported", but nothing else.
If I close the program and start it again it still shows only recipe, that I added by hand, and none imported.

**Comment by WithThisHerring** [comment]
I'm having the same issue in Arch Linux, also with Gourmet version 0.17.4.  Steps to reproduce are exactly as saxon-s states.

**Comment by kirienko** [comment]
Hey folks,
I'm trying to fix broken web-import. There are a lot of examples where web-import doesn't work, but _this particular example_ of @saxon-s does work for me! I use the current master branch (3b4b3b0a84314f1a4cb93b7efe35beaf6b7c4a79).

![image](https://user-images.githubusercontent.com/1487169/79136529-755e0200-7db1-11ea-828b-732eba883f26.png)

![image](https://user-images.githubusercontent.com/1487169/79136569-8575e180-7db1-11ea-9dd1-1ef2a0662900.png)

The result is a recipe added to recipe database.
