### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by New2thissnake** [thinkle/gourmet#924]
I am trying to set this up on my Raspberry Pi 3 Model B+ and I have it set up as follows

/home/pi/GourmetRecipe/

I tried initally to install it but failed with an error.  Researched and found that I needed install so items of which I did and afterword it is still giving the error:

$ python setup.py --help
Traceback (most recent call last):
File "setup.py", line 16, in 
from DistUtilsExtra.command import build_extra, build_i18n, build_icons
ImportError: No module named DistUtilsExtra.command

Like I said, I installed python3-distutils-extra because is it a Python 3.5 also check intltool which was up-to-date.

Any idea as to what I am missing?

Thank you

-RJ

**Comment by thinkle** [comment]
Use python 2

**Comment by MarkP2015** [comment]
Someone needs to write up an explanation about why GRM requires python 2 and a work around.

**Comment by thinkle** [comment]
I'm not sure why this would require a write-up -- python had some
significant changes between 2&3, and pygtk had more dramatic changes still
between it's python 2 and python 3 versions. In short, porting is a
non-trivial task.

**Comment by MarkP2015** [comment]
https://linuxconfig.org/how-to-install-python-in-ubuntu-18-04-bionic-beaver-linux#h6-2-install-python-2-on-ubuntu
I need a list of all Python additions, plugins, extensions, etc. necessary for GRM. Thnx.
