### ISSUE TITLE
Runtime error when launching Gourmet

### ISSUE THREAD

**Issue by alexsquared** [thinkle/gourmet#935]
Have done a fresh install per the INSTALL.md in Ubuntu version 16.04.  When I try to launch gourmet, i receive the following. 

root@ct-ubtrec:~# gourmet

/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
/usr/local/lib/python2.7/dist-packages/gourmet/gtk_extras/LinkedTextView.py:80: GtkWarning: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
  hand_cursor = gtk.gdk.Cursor(gtk.gdk.HAND2)
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 16, in <module>
    from gourmet import GourmetRecipeManager
  File "/usr/local/lib/python2.7/dist-packages/gourmet/GourmetRecipeManager.py", line 7, in <module>
    import prefs, prefsGui, shopgui, reccard
  File "/usr/local/lib/python2.7/dist-packages/gourmet/shopgui.py", line 3, in <module>
    import recipeManager, convert, reccard, prefs
  File "/usr/local/lib/python2.7/dist-packages/gourmet/reccard.py", line 32, in <module>
    import timeScanner
  File "/usr/local/lib/python2.7/dist-packages/gourmet/timeScanner.py", line 5, in <module>
    from gtk_extras import LinkedTextView
  File "/usr/local/lib/python2.7/dist-packages/gourmet/gtk_extras/LinkedTextView.py", line 76, in <module>
    class LinkedTextView (gtk.TextView):
  File "/usr/local/lib/python2.7/dist-packages/gourmet/gtk_extras/LinkedTextView.py", line 80, in LinkedTextView
    hand_cursor = gtk.gdk.Cursor(gtk.gdk.HAND2)
RuntimeError: could not create GdkCursor object

**Comment by saxon-s** [comment]
Hi Alex,

From the screen log it appears that 'python-gtk' is not installed. Run:

$ sudo apt-get update && sudo apt-get upgrade
$ sudo apt-get install python-gtk2

Gourmet requires gtk2 to be installed, see
https://github.com/thinkle/gourmet/blob/master/INSTALL.md for required
packages.

If the above steps don't work, provide a screen capture of all steps
performed.

Regards,

Saxon.
--

**Comment by alexsquared** [comment]
The issue was much more elementary then that.  I had installed it on Ubuntu 18.04.  I created a machine running Debian 9 and installed.  It launches Gourmet now. The only question i have, is how can I access this remotely?   I was hoping to end up with something similar to OpenEats where I can load it up via a web page from any device to modify/view recipes.   Is this possible?

**Comment by saxon-s** [comment]
It appears that the original problem you reported is now resolved. I'm therefore closing this issue. 

In regards to remote access, there is an experimental Django plugin that provide view only recipe access. See issue #933 and PR #936.

**Comment by saxon-s** [comment]
Closing issue as original reported issue is now resolved.
