### ISSUE TITLE
Can't print recipe

### ISSUE THREAD

**Issue by jamaique78** [thinkle/gourmet#951]
I am under Ubuntu 18.04.3 LTS. I want to print a recipe. But when I activate PDF export and print, an error says that the python print plugin is not present.
And it is impossible to find and install such a plugin...
How to print a recipe ?
Except this, all the gourmet app works fine.
Thanks.
PS Excuse my poor english, I'm french...

**Comment by FriedrichFroebel** [comment]
This plugin has been removed from the `gourmet` package by the Ubuntu package maintainers in January 2018, see #909.

**Comment by joelswartz** [comment]
I had the same issue using Linux neon, but just followed the steps in this link to use wget to add stuff and now all is good; can print and export.
https://askubuntu.com/questions/1185579/printing-pdf-export-plugin-for-gourmet-recipe-manager-0-17-4
