### ISSUE TITLE
where is the database library?

### ISSUE THREAD

**Issue by rngoman** [thinkle/gourmet#971]
I might have corrupted the library for Gourmet Recipe, so I tried to reload the program but still have error.  

How do I delete the old database library and start from scratch?
The corruption happened because the computer went into hibernation
![gourmet error](https://user-images.githubusercontent.com/62208465/80818724-5628e800-8b99-11ea-9200-d43bc4f32393.jpg)
.

**Comment by saxon-s** [comment]
The name of the database file is `recipes.db` and it can be found in the following locations:

**Linux:** in your home directory: `~/.gourmet`
**Windows:**  in your user directory: `%APPDATA%`, i.e. `c:\Users\<user>\AppData\Roaming`

**Comment by rngoman** [comment]
Thank you. Now that I have deleted that file, I can run the program. I will have to start scratch but I have always liked this program. Nothing seemed to do as well.

Thank you again for responding. 

Carol
