### ISSUE TITLE
Cannot edit ingredients with umlauts after creating

### ISSUE THREAD

**Issue by cryve** [thinkle/gourmet#976]
### Steps to reproduce
1. Create a new recipe
2. Add an ingredient that has an umlaut (_ä, ö, ü_) or other special German character like _ß_ in its name, e.g.: `Süßkartoffel`
3. Edit the ingredient name after inserting and hit ENTER or click somewhere else to save

### Actual result
The changes have not been saved.

### Expected result.
The changes have been saved.

Tested on Windows 10 with Gourmet v0.17.4

**Comment by cydanil** [comment]
Thanks for this.

This is due to character encoding handling in Python 2, where Gourmet mostly functions with ASCII.

As in Python 3 strings are now unicode, this issue will be resolved in the next Python 3 release :) .
